### ISSUE TITLE
[PROCESS] Terminology Management Tool Assessment

### ISSUE THREAD

**Issue by vinomaster** [trustoverip/concepts-and-terminology#31]
## Issue/Feature Description

What tools meet our needs for our process?
What tools would be easy enough to maintain/use/support?

We need to identify a tool athat will let us:
1. ingest markdown data into a term-data-model for refinement
2. easy refinement of terms for entity relationships, language, concepts models etc...
3. generate multiple output formats...

## Process Thoughts

* [Dictionary Development](https://www.sil.org/dictionaries-lexicography/dictionary-development-process)
* [Terminology Management](https://www.sdltrados.com/solutions/terminology-management/)

## Tool Research

Some to consider but not exhaustive....

* [Open DTL](http://apelon-dts.sourceforge.net/)
* [Flex](https://lingtran.net/Flex-work-flow-diagram?structure=Navmenu)
* [TemaTeres](https://sourceforge.net/projects/tematres/)
* [TBXTools - Python class for Terminology Extraction and Management](https://sourceforge.net/projects/tbxtools/)

**Comment by sankarshanmukhopadhyay** [comment]
> ## Issue/Feature Description
> 
> What tools meet our needs for our process?
> What tools would be easy enough to maintain/use/support?
>

For purposes of this issue/ticket it would be appropriate to record the models of maintenance and support which are being considered. As an example, is it a better fit to consider a hosted/hosted+managed tool|service which the group uses through a some agreement and/or SLA.
 
> We need to identify a tool athat will let us:
> 
>     1. ingest markdown data into a term-data-model for refinement
> 
>     2. easy refinement of terms for entity relationships, language, concepts models etc...
> 
>     3. generate multiple output formats...

Similarly for this point - an indicative list of output formats would be good to have.

**Comment by vinomaster** [comment]
What about the ability to handle perma-links so that authors can easily and constantly reuse terms?

**Comment by dhh1128** [comment]
Notes on tools:

OpenDTL is very old/stale. Windows -- and old Windows at that (XP through 2008). Web site last updated 7 years ago. It does have approximately the right types of features, but is a standalone application rather than a collaborative web app. We'd have to set up a funky sharing strategy. I do not recommend it.

Flex is a tool for field linguists to build bilingual dictionaries. It doesn't quite fit our problem, although it overlaps it about 50%. It is also a bit stale and lacks robust support and documentation.

TemaTres (vocabularyserver.com) has a broader set of features than the first two, and they correspond nicely to the problem we're trying to solve. It is also a web app, which would allow collaboration more easily than OpenDTL. However, a closer look at its SourceForge page reveals that its 16 reviews were written in 2013-2014. It has 9 logged bugs that haven't been updated for years, with 0 bugs closed. There was a new build produced a year ago, but activity seems minimal. I think if it were a vibrant project, it might be a reasonable tool candidate, but I don't think it's vibrant.

TBXTools might be a useful library if we decide to write python scripts to help us extract terminology, but it is not a tool in and of itself. (The SourceForge link given above should be updated to its more recent activity on github: https://github.com/aoliverg/TBXTools).

AFAIK, industrial-strength, maintained terminology management tools used by professional terminologists fall into two main categories:

1. Proprietary systems developed in-house. I believe [Termium](https://www.btb.termiumplus.gc.ca/tpv2alpha/alpha-eng.html?lang=eng) in Canada is a great example of this type of tool. The World Health Organization is another example of an org with sophisticated terminology management goals that maintains internal tools. (See [here](https://www.who.int/healthsystems/hss_glossary/en/), for example.)

2. Commercial products. I believe the prototypical example of this category is [SDL MultiTerm](https://www.sdltrados.com/products/multiterm-desktop/). This product has a long genealogy. I first encountered it circa 1993. It has been sold and rebranded, and is now part of a larger computer-assisted translation tool suite. It has very sophisticated features that cover nearly all of our use cases. However, it is not focused on the emitting of glossaries; its goal is to help translators be more efficient and consistent. I believe it does not allow permalinks to data items in the way we'd like; we'd have to spend some effort configuring integration/import/export.

Category 1 tools are not available to us. Category 2 tools tend to be expensive, and to have a deep learning curve.

My recommendation is that we develop our own tool. I think the set of features we need is not overly large, and that we can build them easily on top of github. The cost/effort/time to develop will not be any greater than the cost/effort/time to deploy and learn a third-party tool (and may be much less), we'll know we have what we need, and we will know the tool when we are done.

**Comment by vinomaster** [comment]
@dhh1128 has [offered an assessment to match the above recommendation](https://docs.google.com/presentation/d/1CzJ5G6qTQ06rohPHGUj9887XtB19EK-FUMhWlmgRvy8/edit). I am all for building our own if we have committed resources.

**Comment by dhh1128** [comment]
WG voted on general direction WRT this question, in public meeting on 2020-11-23.
